"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .dailyavailability import DailyAvailability
from .tasktemplate_input import TaskTemplateInput
from dataclasses_json import Undefined, dataclass_json
from typing import Dict, List, Optional
from vibrato import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CampaignInput:
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    task_property_to_contact_field: Dict[str, str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('task_property_to_contact_field') }})
    task_template_uuid: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('task_template_uuid') }})
    daily_availability: List[DailyAvailability] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('daily_availability') }})
    timezone: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('timezone') }})
    task_template: Optional[TaskTemplateInput] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('task_template'), 'exclude': lambda f: f is None }})
    paused: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('paused'), 'exclude': lambda f: f is None }})
    

