"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from typing import Dict, Optional
from vibrato import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateFromTaskTemplate:
    UNSET='__SPEAKEASY_UNSET__'
    task_template_uuid: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('task_template_uuid') }})
    recipient_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('recipient_name') }})
    recipient_phone_number: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('recipient_phone_number') }})
    recipient_country_code: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('recipient_country_code') }})
    api_idempotency_key: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('api_idempotency_key'), 'exclude': lambda f: f is CreateFromTaskTemplate.UNSET }})
    task_template_parameters: Optional[Dict[str, str]] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('task_template_parameters'), 'exclude': lambda f: f is CreateFromTaskTemplate.UNSET }})
    contact_uuid: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('contact_uuid'), 'exclude': lambda f: f is CreateFromTaskTemplate.UNSET }})
    voice_id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('voice_id'), 'exclude': lambda f: f is None }})
    voice_clone_uuid: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('voice_clone_uuid'), 'exclude': lambda f: f is CreateFromTaskTemplate.UNSET }})
    r"""Voice clone identifier from your account"""
    leave_voicemail_message: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('leave_voicemail_message'), 'exclude': lambda f: f is None }})
    voicemail_message: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('voicemail_message'), 'exclude': lambda f: f is None }})
    handoff_phone_number_uuid: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('handoff_phone_number_uuid'), 'exclude': lambda f: f is CreateFromTaskTemplate.UNSET }})
    handoff_phone_number: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('handoff_phone_number'), 'exclude': lambda f: f is None }})
    r"""Full handoff phone number including country code (e.g. 17607916516)"""
    handoff_condition: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('handoff_condition'), 'exclude': lambda f: f is CreateFromTaskTemplate.UNSET }})
    retries: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('retries'), 'exclude': lambda f: f is None }})
    retry_delay_seconds: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('retry_delay_seconds'), 'exclude': lambda f: f is None }})
    scheduled_at: Optional[datetime] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('scheduled_at'), 'encoder': utils.datetimeisoformat(True), 'decoder': dateutil.parser.isoparse, 'exclude': lambda f: f is CreateFromTaskTemplate.UNSET }})
    outbound_twilio_phone_number_uuid: Optional[str] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('outbound_twilio_phone_number_uuid'), 'exclude': lambda f: f is CreateFromTaskTemplate.UNSET }})
    outbound_twilio_phone_number: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('outbound_twilio_phone_number'), 'exclude': lambda f: f is None }})
    r"""Full outbound phone number including country code (e.g. 17607916516)"""
    

