workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    vibrato-pub-api:
        inputs:
            - location: ../vibrato-app/vibrato/openapi/public_api.yaml
        registry:
            location: registry.speakeasyapi.dev/vibrato-cd9/vibrato-2/vibrato-pub-api
targets:
    my-first-target:
        target: python
        source: vibrato-pub-api
