workflowVersion: 1.0.0
speakeasyVersion: 1.335.0
sources:
    vibrato-pub-api:
        inputs:
            - location: ../vibrato-app/vibrato/openapi/public_api.yaml
        registry:
            location: registry.speakeasyapi.dev/vibrato-cd9/vibrato-2/vibrato-pub-api
targets:
    vibrato-python:
        target: python
        source: vibrato-pub-api
        output: .
    terraform-provider-vibrato:
        target: terraform
        source: vibrato-pub-api
        output: ../terraform-provider-vibrato
