"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata


@dataclasses.dataclass
class DeleteCallRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class DeleteCallResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    

