"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import call as components_call
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class EndCallRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class EndCallResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    call: Optional[components_call.Call] = dataclasses.field(default=None)
    r"""Call ended and the call's details are returned."""
    

