"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import transcript as components_transcript
from typing import Optional


@dataclasses.dataclass
class GetTranscriptRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetTranscriptResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    transcript: Optional[components_transcript.Transcript] = dataclasses.field(default=None)
    r"""Transcript of the call."""
    

