"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import calllist as components_calllist
from ...models.components import httpmetadata as components_httpmetadata
from typing import Optional


@dataclasses.dataclass
class ListCallsResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    call_list: Optional[components_calllist.CallList] = dataclasses.field(default=None)
    r"""A list of calls."""
    

