"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import tasktemplate as components_tasktemplate
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclasses.dataclass
class RetrieveTaskTemplateRequest:
    uuid: str = dataclasses.field(metadata={'path_param': { 'field_name': 'uuid', 'style': 'simple', 'explode': False }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RetrieveTaskTemplateResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    task_template: Optional[components_tasktemplate.TaskTemplate] = dataclasses.field(default=None)
    r"""A single task template."""
    

